class AIModel:
    def translate(self, text):
        # Expanded translations dictionary
        translations = {
            "hello": "kumusta",
            "thank you": "salamat",
            "goodbye": "paalam",
            "please": "pakiusap",
            "sorry": "paumanhin",
            "yes": "oo",
            "no": "hindi",
            "how are you": "kamusta ka",
            "how old are you": "ilang taon ka na",
            "what is your name": "ano ang pangalan mo",
            "my name is": "ang pangalan ko ay",
            "where are you from": "saan ka nagmula",
            "good morning": "magandang umaga",
            "good afternoon": "magandang hapon",
            "good evening": "magandang gabi",
            "i love you": "mahal kita",
            "congratulations": "maligayang bati",
            "happy birthday": "maligayang kaarawan",
            "excuse me": "makikiraan",
            "how much": "magkano",
            "help": "tulong",
            "do you speak english": "nagsasalita ka ba ng ingles",
            "i don't understand": "hindi ko naiintindihan",
            "bathroom": "banyo",
            "water": "tubig",
            "food": "pagkain",
            "where is": "nasaan",
            "i'm lost": "naliligaw ako",
            "beautiful": "maganda",
            "friend": "kaibigan",
            "family": "pamilya",
            "i am hungry": "gutom ako",
            "i am thirsty": "uhaw ako",
            "doctor": "doktor",
            "police": "pulis",
            "fire": "apoy",
            "what time is it": "anong oras na",
            "where is the hotel": "nasaan ang hotel",
            "where is the restaurant": "nasaan ang restawran",
            "open": "bukas",
            "closed": "sarado",
            "one": "isa",
            "two": "dalawa",
            "three": "tatlo",
            "four": "apat",
            "five": "lima",
            "six": "anim",
            "seven": "pito",
            "eight": "walo",
            "nine": "siyam",
            "ten": "sampu",
        }
        
        return translations.get(text.lower(), "Translation not available")
